const Diff = require('diff');
const { transporter } = require('./sendEmail');
require('dotenv').config();

async function sendDiffEmail(majorChanges, recipients = null) {
  if (!majorChanges || majorChanges.length === 0) return;

  let htmlContent = `
    <div style="font-family: Arial, sans-serif; color: #333;">
      <h2 style="color: #2c3e50; border-bottom: 2px solid #eee; padding-bottom: 10px;">Detailed Content Change Report</h2>
      <p>The following pages have detected significant content changes (>20%).</p>
  `;

  for (const change of majorChanges) {
    const { url, oldText, newText } = change;
    
    // Generate diff
    const diff = Diff.diffLines(oldText, newText);
    
    htmlContent += `
      <div style="margin-bottom: 30px; border: 1px solid #ddd; border-radius: 5px; overflow: hidden;">
        <div style="background: #f8f9fa; padding: 10px; border-bottom: 1px solid #ddd;">
          <strong>${url}</strong>
        </div>
        <div style="padding: 10px; font-family: monospace; white-space: pre-wrap; font-size: 12px; max-height: 500px; overflow-y: auto;">
    `;

    diff.forEach((part) => {
      // green for additions, red for deletions
      // grey for common parts
      const color = part.added ? '#e6ffec' :
        part.removed ? '#ffebe9' : 'transparent';
      
      const textColor = part.added || part.removed ? '#24292e' : '#666';
      
      // Escape HTML to prevent injection and rendering issues
      const escapedValue = part.value
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#039;");

      htmlContent += `<span style="background-color: ${color}; color: ${textColor}; display: block;">${escapedValue}</span>`;
    });

    htmlContent += `
        </div>
      </div>
    `;
  }

  htmlContent += `
      <div style="margin-top: 30px; font-size: 0.8em; color: #999; border-top: 1px solid #eee; padding-top: 10px;">
        Generated by Hibbett SEO Monitor • ${new Date().toLocaleString()}
      </div>
    </div>
  `;

  const defaultRecipients = 'marzuaga@peakactivity.com, vijaylaxmi.chauhan@hibbett.com, tre.kitchen@hibbett.com, areynolds@peakactivity.com';

  const mailOptions = {
    from: `"SEO Monitor" <${process.env.EMAIL_USER}>`,
    // Reuse the same recipients as the main email
    to: recipients || defaultRecipients,
    subject: 'SEO Monitor - Detailed Content Changes',
    html: htmlContent,
  };

  try {
    let info = await transporter.sendMail(mailOptions);
    console.log('Diff Email sent: %s', info.messageId);
  } catch (error) {
    console.error('Error sending diff email:', error);
  }
}

module.exports = { sendDiffEmail };
